color0   #f7fbf1
color1   #d23434
color2   #238521
color3   #9d632e
color4   #347f27
color5   #1e591a
color6   #3c6939
color7   #2e2e2e
color8   #4a4a4a
color9   #e55b5b
color10   #309c2e
color11   #b3773e
color12   #427d3e
color13   #50a328
color14   #38a35b
color15   #1a1a1a

cursor #191d17
cursor_text_color #424940

foreground            #191d17
background            #f7fbf1
selection_foreground  #ffffff
selection_background  #baccb3
url_color             #3c6939